"""add_translation_cache

Revision ID: 0526a8252a5a
Revises: d270add2c830
Create Date: 2026-06-28 14:15:23.282239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0526a8252a5a'
down_revision: Union[str, Sequence[str], None] = 'd270add2c830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation_cache',
    sa.Column('source_hash', sa.String(length=64), nullable=False, comment='SHA256 of source text'),
    sa.Column('source_lang', sa.String(length=10), nullable=False),
    sa.Column('target_lang', sa.String(length=10), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translation_cache_id'), 'translation_cache', ['id'], unique=False)
    op.create_index(op.f('ix_translation_cache_source_hash'), 'translation_cache', ['source_hash'], unique=False)
    op.create_index(op.f('ix_translation_cache_target_lang'), 'translation_cache', ['target_lang'], unique=False)
    op.create_index('ix_translation_lookup', 'translation_cache', ['source_hash', 'target_lang'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_translation_lookup', table_name='translation_cache')
    op.drop_index(op.f('ix_translation_cache_target_lang'), table_name='translation_cache')
    op.drop_index(op.f('ix_translation_cache_source_hash'), table_name='translation_cache')
    op.drop_index(op.f('ix_translation_cache_id'), table_name='translation_cache')
    op.drop_table('translation_cache')
    # ### end Alembic commands ###
