"""add_chapter_volume

Revision ID: 1b02f66a95bc
Revises: a752721e5870
Create Date: 2026-06-27 14:51:33.721541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b02f66a95bc'
down_revision: Union[str, Sequence[str], None] = 'a752721e5870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('volume', sa.String(length=255), nullable=True, comment='Volume/section name (e.g. 第一卷 七玄门风云)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapters', 'volume')
    # ### end Alembic commands ###
