"""add_sites_table

Revision ID: 354e21e3b916
Revises: 1b02f66a95bc
Create Date: 2026-06-28 10:22:43.239734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '354e21e3b916'
down_revision: Union[str, Sequence[str], None] = '1b02f66a95bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_unique_title', table_name='novels')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_unique_title', 'novels', ['title'], unique=True)
    # ### end Alembic commands ###
