"""add_translate_enabled_to_sites

Revision ID: 5443dc1b2227
Revises: 0c9a47e623bb
Create Date: 2026-06-29 16:09:57.471901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5443dc1b2227'
down_revision: Union[str, Sequence[str], None] = '0c9a47e623bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ft_chapters_search', table_name='chapters', mysql_prefix='FULLTEXT', mysql_with_parser='ngram')
    op.add_column('sites', sa.Column('translate_enabled', sa.Boolean(), nullable=False, comment='Enable real-time translation via LibreTranslate'))
    op.create_index(op.f('ix_translation_cache_target_lang'), 'translation_cache', ['target_lang'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translation_cache_target_lang'), table_name='translation_cache')
    op.drop_column('sites', 'translate_enabled')
    op.create_index('ft_chapters_search', 'chapters', ['title'], unique=False, mysql_prefix='FULLTEXT', mysql_with_parser='ngram')
    # ### end Alembic commands ###
