"""add_content_file

Revision ID: a752721e5870
Revises: a49c9cb0b1f9
Create Date: 2026-06-27 13:39:48.045242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a752721e5870'
down_revision: Union[str, Sequence[str], None] = 'a49c9cb0b1f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('content_file', sa.String(length=512), nullable=True, comment='Path to compressed content file (e.g. data/content/ab/abc.../xyz.gz)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapters', 'content_file')
    # ### end Alembic commands ###
