"""add_url_patterns_pagination_link_rings

Revision ID: b7607ea46936
Revises: 354e21e3b916
Create Date: 2026-06-28 11:33:13.301819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b7607ea46936'
down_revision: Union[str, Sequence[str], None] = '354e21e3b916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_ring_targets',
    sa.Column('ring_id', sa.String(length=36), nullable=False),
    sa.Column('source_site_id', sa.String(length=36), nullable=True),
    sa.Column('source_novel_id', sa.String(length=36), nullable=True, comment="Show link on this novel's pages; NULL = all novels on source_site"),
    sa.Column('target_site_id', sa.String(length=36), nullable=True, comment='Link to this site; NULL = same site as source'),
    sa.Column('target_novel_id', sa.String(length=36), nullable=True),
    sa.Column('target_url', sa.String(length=500), nullable=True, comment='Custom URL override (e.g., external link)'),
    sa.Column('anchor_text', sa.String(length=200), nullable=False, comment='Anchor text template'),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_ring_targets_id'), 'link_ring_targets', ['id'], unique=False)
    op.create_index(op.f('ix_link_ring_targets_ring_id'), 'link_ring_targets', ['ring_id'], unique=False)
    op.create_table('link_rings',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ring_type', sa.String(length=30), nullable=False, comment='cross_site | same_site_books | cross_site_books | custom'),
    sa.Column('site_id', sa.String(length=36), nullable=True, comment='NULL = applies to all sites'),
    sa.Column('max_links', sa.Integer(), nullable=False, comment='Max links to show per page'),
    sa.Column('display_mode', sa.String(length=20), nullable=False, comment='sidebar | footer | inline | popup'),
    sa.Column('link_format', sa.String(length=500), nullable=False, comment='Template: {title}, {author}, {site_name}, {chapter} supported'),
    sa.Column('open_new_tab', sa.Boolean(), nullable=False),
    sa.Column('nofollow', sa.Boolean(), nullable=False),
    sa.Column('selection_rules', sa.JSON(), nullable=True, comment='\n    Rules for auto-selecting source and target books.\n    {\n        "source": {"site_ids": [], "novel_ids": [], "category_ids": [], "exclude_novel_ids": []},\n        "target": {"site_ids": [], "novel_ids": [], "category_ids": [],\n                   "match_by": "category", "exclude_novel_ids": []},\n        "on_pages": ["novel_detail", "chapter_read", "home"]\n    }\n    '),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_rings_id'), 'link_rings', ['id'], unique=False)
    op.create_index(op.f('ix_link_rings_site_id'), 'link_rings', ['site_id'], unique=False)
    op.add_column('sites', sa.Column('url_patterns', sa.JSON(), nullable=True, comment='\n    URL rewrite patterns for this site. Example:\n    {\n        "novel_detail": "/novel/{id}.html",\n        "chapter_list": "/novel/{id}/chapters/",\n        "chapter_read": "/chapter/{id}.html",\n        "category_list": "/category/{id}/",\n        "search": "/search/{keyword}/"\n    }\n    Leave null to use default patterns (/novel/{id}, /chapter/{id}, etc.)\n    '))
    op.add_column('sites', sa.Column('chapter_pagination', sa.JSON(), nullable=True, comment='\n    Chapter pagination config for this site. Example:\n    {\n        "enabled": true,\n        "method": "word_count",      // "word_count" | "page_count" | "none"\n        "words_per_page": 3000,       // split every N words\n        "pages_per_chapter": null,    // or split into N fixed pages\n        "show_page_nav": true,        // show "Page 1/5" navigation\n        "page_param": "page",         // query param name: ?page=2\n        "canonical_first_page": true  // page 1 uses canonical URL without ?page=\n    }\n    '))
    op.add_column('sites', sa.Column('link_wheel', sa.JSON(), nullable=True, comment='\n    Per-site link wheel defaults. Global link rings can override these.\n    {\n        "enabled": true,\n        "max_links_per_page": 8,\n        "link_section": "sidebar",   // "sidebar" | "footer" | "inline" | "popup"\n        "open_new_tab": true,\n        "nofollow": false\n    }\n    '))
    op.alter_column('sites', 'template',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'default'"))
    op.alter_column('sites', 'offset_val',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='Novel offset for content differentiation',
               existing_server_default=sa.text("'0'"))
    op.alter_column('sites', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('sites', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('sites', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index('domain', table_name='sites')
    op.drop_index('idx_domain', table_name='sites')
    op.create_index(op.f('ix_sites_domain'), 'sites', ['domain'], unique=True)
    op.create_index(op.f('ix_sites_id'), 'sites', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sites_id'), table_name='sites')
    op.drop_index(op.f('ix_sites_domain'), table_name='sites')
    op.create_index('idx_domain', 'sites', ['domain'], unique=False)
    op.create_index('domain', 'sites', ['domain'], unique=True)
    op.alter_column('sites', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('sites', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('sites', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('sites', 'offset_val',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='Novel offset for content differentiation',
               existing_server_default=sa.text("'0'"))
    op.alter_column('sites', 'template',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'default'"))
    op.drop_column('sites', 'link_wheel')
    op.drop_column('sites', 'chapter_pagination')
    op.drop_column('sites', 'url_patterns')
    op.drop_index(op.f('ix_link_rings_site_id'), table_name='link_rings')
    op.drop_index(op.f('ix_link_rings_id'), table_name='link_rings')
    op.drop_table('link_rings')
    op.drop_index(op.f('ix_link_ring_targets_ring_id'), table_name='link_ring_targets')
    op.drop_index(op.f('ix_link_ring_targets_id'), table_name='link_ring_targets')
    op.drop_table('link_ring_targets')
    # ### end Alembic commands ###
