"""add_language_to_sites

Revision ID: d270add2c830
Revises: fe169271913a
Create Date: 2026-06-28 12:53:07.415763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd270add2c830'
down_revision: Union[str, Sequence[str], None] = 'fe169271913a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('language', sa.String(length=10), nullable=False, comment='Site language code: zh,en,ja,ko,fr,de,es,pt,ru,ar,th,vi,id,it,tr,hi,ms'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'language')
    # ### end Alembic commands ###
