"""add_recommend_modules

Revision ID: fe169271913a
Revises: b7607ea46936
Create Date: 2026-06-28 11:58:27.735253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fe169271913a'
down_revision: Union[str, Sequence[str], None] = 'b7607ea46936'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('link_ring_targets', 'source_novel_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment="Show link on this novel's pages; NULL = all novels on source_site",
               existing_nullable=True)
    op.alter_column('link_ring_targets', 'target_site_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='Link to this site; NULL = same site as source',
               existing_nullable=True)
    op.alter_column('link_ring_targets', 'target_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment=None,
               existing_comment='Custom URL override (e.g., external link)',
               existing_nullable=True)
    op.alter_column('link_ring_targets', 'anchor_text',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='Anchor text template',
               existing_nullable=False)
    op.alter_column('link_rings', 'max_links',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Max links to show per page',
               existing_nullable=False)
    op.alter_column('link_rings', 'display_mode',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment=None,
               existing_comment='sidebar | footer | inline | popup',
               existing_nullable=False)
    op.alter_column('link_rings', 'link_format',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment=None,
               existing_comment='Template: {title}, {author}, {site_name}, {chapter} supported',
               existing_nullable=False)
    op.alter_column('link_rings', 'selection_rules',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='\n    Rules for auto-selecting source and target books.\n    {\n        "source": {"site_ids": [], "novel_ids": [], "category_ids": [], "exclude_novel_ids": []},\n        "target": {"site_ids": [], "novel_ids": [], "category_ids": [],\n                   "match_by": "category", "exclude_novel_ids": []},\n        "on_pages": ["novel_detail", "chapter_read", "home"]\n    }\n    ',
               existing_nullable=True)
    op.add_column('sites', sa.Column('recommend_modules', sa.JSON(), nullable=True, comment='\n    Per-page module toggles and settings. null = all defaults (enabled).\n    {\n        "home": {\n            "hero_carousel": {"enabled": true},\n            "category_sections": {"enabled": true, "max_categories": 9},\n            "latest_updates": {"enabled": true, "count": 25},\n            "hot_ranking": {"enabled": true, "count": 15},\n            "friend_links": {"enabled": true},\n            "link_wheel": {"enabled": true}\n        },\n        "novel_detail": {\n            "friend_links": {"enabled": true},\n            "link_wheel": {"enabled": true}\n        },\n        "chapter_read": {\n            "random_recommend": {"enabled": true, "count": 5},\n            "reader_toolbar": {"enabled": true},\n            "link_wheel": {"enabled": true}\n        },\n        "chapter_list": {\n            "link_wheel": {"enabled": true}\n        },\n        "search": {\n            "link_wheel": {"enabled": true}\n        },\n        "book_library": {\n            "link_wheel": {"enabled": true}\n        }\n    }\n    '))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'recommend_modules')
    op.alter_column('link_rings', 'selection_rules',
               existing_type=mysql.JSON(),
               comment='\n    Rules for auto-selecting source and target books.\n    {\n        "source": {"site_ids": [], "novel_ids": [], "category_ids": [], "exclude_novel_ids": []},\n        "target": {"site_ids": [], "novel_ids": [], "category_ids": [],\n                   "match_by": "category", "exclude_novel_ids": []},\n        "on_pages": ["novel_detail", "chapter_read", "home"]\n    }\n    ',
               existing_nullable=True)
    op.alter_column('link_rings', 'link_format',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='Template: {title}, {author}, {site_name}, {chapter} supported',
               existing_nullable=False)
    op.alter_column('link_rings', 'display_mode',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='sidebar | footer | inline | popup',
               existing_nullable=False)
    op.alter_column('link_rings', 'max_links',
               existing_type=mysql.INTEGER(),
               comment='Max links to show per page',
               existing_nullable=False)
    op.alter_column('link_ring_targets', 'anchor_text',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='Anchor text template',
               existing_nullable=False)
    op.alter_column('link_ring_targets', 'target_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='Custom URL override (e.g., external link)',
               existing_nullable=True)
    op.alter_column('link_ring_targets', 'target_site_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='Link to this site; NULL = same site as source',
               existing_nullable=True)
    op.alter_column('link_ring_targets', 'source_novel_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment="Show link on this novel's pages; NULL = all novels on source_site",
               existing_nullable=True)
    # ### end Alembic commands ###
